site_name: BeMine Wedding Website

nav:
  

  - Category:
      - Create Category: category/create.md
      - Update Category: category/update.md
      - Get Categories: category/getCategories.md
      - Get Single Category: category/readSingle.md
      - Delete Category: category/delete.md

  - Users:
      - Create User: users/create.md
      - Login User: users/login.md
      - Get Users: users/getUsers.md
      - Get Single User: users/readSingle.md
      - Update User: users/update.md
      - Update Password: users/updatePassword.md

  - Vendor:
      - Create Vendor: vendor/create.md
      - Delete Vendor: vendor/delete.md
      - Get Vendor: vendor/getVendors.md
      - Get Single Vendor: vendor/readSingle.md
      - Update Vendor: vendor/update.md

  - Wedding Plan:
      - Create Wedding Plan: weddingPlan/create.md
      - Get Wedding Plan: weddingPlan/getWeddingPlan.md
      - Get Single Wedding Plan: weddingPlan/readSingle.md
      - Get Wedding Plan by User ID: weddingPlan/readSingleByUserId.md
      - Update Wedding Plan: weddingPlan/update.md
      - Update Budget: weddingPlan/updateBudget.md
      - Update Guest Count: weddingPlan/updateGuestCount.md
      - Update Partner Nickname: weddingPlan/updatePartnerNickname.md
      - Update User Nickname: weddingPlan/updateUserNickname.md
      - Update Wedding Date: weddingPlan/updateWeddingDate.md

  - Wedding Plan Task:
      - Create Wedding Plan Task: weddingPlanTask/create.md
      - Create Is Selected list: weddingPlanTask/createIsSelected.md
      - Get Wedding Plan Tasks: weddingPlanTask/getWeddingPlanTask.md
      - Get Single Wedding Plan Task: weddingPlanTask/readSingle.md
      - Get Task By Wedding Plan ID: weddingPlanTask/readTasksByWeddingPlanId.md
      - Update Wedding Plan Task: weddingPlanTask/update.md
      - Update Is Completed: weddingPlanTask/updateIsCompleted.md
      - Update Is Selected: weddingPlanTask/updateIsSelected.md


extra_css:
      - style/style_doc.css
